### ISSUE TITLE
Imputation of uncontested results

### ISSUE THREAD

**Issue by hjohns12** [PlanScore/Model-Generator#1]
This is more of a question than an issue. What is your treatment of uncontested races? I know that in some poli-sci research circles it's common practice to impute the vote share in uncontested races to 75% win-25% loss. Looking at the `run_planscore_model.R` file, that doesn't appear to have been done. Any reasoning why or why not? 

Thank you so much for this great work, as always!

**Comment by emcghee73** [comment]
The "party.pc" function near the top of the code has a section that assigns all uncontested races to missing data, which means they automatically get dropped from the lm() function later on.  But then the model estimates are used to generate predictions for the entire population of precincts.  So the process imputes uncontested races that way.  I'm uploading a new version of the code that annotates with this information.

**Comment by migurski** [comment]
I merged a short addition to the model that documents uncontested races in https://github.com/PlanScore/Model-Generator/pull/2.
